export const beritas = [
  {
    title: 'Dolor Sit Amet Consectetur Adipisicing',
    desc: `\t\tLorem ipsum dolor sit amet, consectetur adipisicing elit. Provident, laboriosam magni quaerat velit explicabo eveniet, tempora suscipit a voluptatibus repellendus dolorum aliquam iusto quisquam. Sequi saepe dignissimos nobis, accusamus libero, dolores doloremque atque commodi pariatur reprehenderit minima exercitationem debitis laborum velit reiciendis. Ex atque vero aliquam, ipsa id corrupti architecto iure nesciunt ab voluptates. Facilis cum possimus dolor repellat sint inventore deleniti, accusantium dolore, necessitatibus officia voluptatum quod magni aperiam. Architecto, voluptate incidunt! Tempore suscipit fugiat rerum reprehenderit quos. Nostrum iste ut a obcaecati tenetur alias recusandae, consequatur, perferendis harum numquam. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit. Explicabo nemo dolorum, nihil soluta, commodi quaerat excepturi odit iure sunt distinctio temporibus, nobis aliquid aperiam voluptatibus velit. Enim exercitationem, labore mollitia ut officia incidunt, expedita iusto beatae non provident cum distinctio aspernatur aliquam debitis. Quod quasi iusto, optio deleniti ipsa dolorem reprehenderit voluptatum at qui voluptatem est iure, tempora eius hic! Facere dolorem sint, magnam numquam culpa impedit, recusandae veniam omnis harum nihil porro error nisi aut quae. Eos aliquid, perspiciatis ullam recusandae reprehenderit, quas voluptate tempora libero. Ex explicabo autem doloribus laboriosam incidunt tempora non, in est dolorum sequi, a temporibus ea, id sint, harum sapiente quibusdam veritatis! Inventore, officia alias debitis quasi temporibus, suscipit beatae consequuntur optio molestiae facilis in cum sequi labore, mollitia, ipsa necessitatibus rem! Sequi aut reiciendis tenetur voluptas error, dolore quod dolor, rerum vero voluptatum, magni consequatur.
        
    \t\tFugit error voluptates voluptatibus expedita pariatur quasi magnam id commodi iure numquam. Deserunt tempora debitis, totam aliquam itaque excepturi suscipit repellendus. Laboriosam aperiam ratione voluptas impedit eius, fuga, dolores molestias! Alias ut consectetur explicabo, saepe cum vel pariatur. Sed pariatur, dignissimos placeat quaerat maiores sint numquam omnis ex! Optio voluptatibus dolorum officia a deserunt alias, totam dolorem explicabo quia quaerat hic repellat, quos est eaque! Molestiae dolorum explicabo nisi sunt molestias, quisquam hic assumenda vero voluptatibus beatae. Veniam qui beatae officiis atque tempora placeat numquam quaerat nulla. Laboriosam voluptates saepe alias, iste! Rerum quia incidunt perferendis aut soluta explicabo at atque dolorem, provident quos dolorum quas hic. Ut omnis sit dignissimos voluptates obcaecati dolorum. Beatae, rem magnam, molestiae optio sint blanditiis ea, numquam quia eveniet distinctio, repudiandae, reprehenderit molestias? Architecto cum maiores officia, omnis odit doloribus repellat, distinctio, alias soluta, ipsam incidunt ex quas nihil? Neque sint soluta veniam ut nobis iusto doloremque, temporibus aperiam iure quos accusamus molestias nulla, facilis. In ad necessitatibus, cumque ut dolores voluptatum consectetur aspernatur hic distinctio blanditiis ipsa aut, beatae! Repudiandae, voluptates veniam tenetur excepturi obcaecati! Eum, deserunt perferendis voluptatibus dolorum, soluta officiis, sequi, explicabo iure optio. Maxime, nobis dolorem sunt reiciendis molestias explicabo tempora? Tempore doloribus sit soluta eveniet aperiam alias inventore! Iure omnis sint blanditiis ea saepe sunt beatae, rem optio veniam, ad totam vel quasi repellendus. Reprehenderit voluptates laborum sapiente incidunt eveniet excepturi! Veritatis, laboriosam consequatur recusandae soluta nobis quaerat omnis voluptate officia, impedit veniam, voluptatibus explicabo. Adipisci distinctio obcaecati error quisquam veritatis consequatur non necessitatibus officia.`,
    href: '/dolor-sit-amet-consectetur-adipisicing',
    image: 'https://picsum.photos/seed/picsum/200/300',
  },
  {
    title: 'Sed Ut Perspiciatis Unde Omnis Iste',
    desc: `\t\tSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit. Voluptatibus, accusamus excepturi? Reprehenderit dolorum iusto repudiandae inventore, neque aliquam rem id numquam natus qui ullam doloribus consequatur vel porro totam, eius suscipit vero! Ex quas explicabo, dolore dolor tempora aspernatur voluptate alias. Placeat, ab cum sit incidunt sequi optio assumenda voluptates, veritatis nam, provident impedit a. Iure sint facere aspernatur quidem obcaecati, pariatur est dolores? Maiores fuga consequatur officiis obcaecati saepe, quos necessitatibus culpa dolorem, rerum assumenda minima eveniet. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.
        
    \tAt vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi. Ipsum veritatis molestias, voluptates hic asperiores quidem suscipit dolore reprehenderit, quibusdam impedit, sed facilis optio esse, voluptatibus delectus consequuntur. Et cum eos veniam optio pariatur laboriosam, magnam quisquam deserunt excepturi sint quas. Similique, saepe laborum dignissimos rerum doloribus optio assumenda reiciendis dolor incidunt, iste molestias! Eius vitae, numquam iure, sequi asperiores sapiente. Repellendus reiciendis inventore voluptas explicabo odit, quisquam nulla non laboriosam delectus ab, id deserunt distinctio esse, facilis corrupti! Molestiae non deserunt inventore consectetur reiciendis. Iure doloribus quidem reiciendis, optio necessitatibus nobis beatae explicabo voluptatem laboriosam. Eius dignissimos saepe magnam incidunt, obcaecati dolor, sint eveniet harum vero dolore deserunt, ex iusto, dolorum numquam velit voluptatem omnis. Recusandae vero itaque, ut ex nobis quia, temporibus voluptatem.`,
    href: '/sed-ut-perspiciatis-unde-omnis-iste',
    image: 'https://picsum.photos/seed/picsum/200/300',
  },
  {
    title: 'Labore Et Dolore Magnam Aliquam',
    desc: `\t\tLabore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident. Quod, necessitatibus! Qui cumque voluptates dolor amet magnam, itaque sunt impedit dolorem reprehenderit hic, velit mollitia deserunt ex beatae, esse nostrum tempore. Facilis fuga id delectus accusantium obcaecati magnam praesentium! Consectetur impedit voluptatum quaerat repellendus aliquam nobis quas officia, eveniet iure porro. Nulla aperiam corrupti a laboriosam, sequi minus deleniti obcaecati aut! Omnis tempora cum esse beatae dignissimos velit, provident unde placeat ipsam harum asperiores quasi voluptatibus. Velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Illum qui dolorem eum fugiat quo voluptas nulla pariatur.
    
    \tAsperiores aliquid quaerat, non totam optio porro, magni laborum, corrupti dignissimos. Sequi consequatur, voluptatem quaerat eius molestiae saepe, magnam optio rerum aliquam. Eius non distinctio sunt suscipit totam quae impedit atque, veritatis, doloribus? Tempore, accusantium.Facilis sunt deserunt reiciendis, eveniet ipsa voluptates. Quod debitis, atque odit sequi voluptatum, obcaecati vero dolorum impedit facilis veniam, quaerat tempora? Magnam distinctio dolore voluptatum alias error ut! Optio, voluptatibus veritatis tenetur suscipit doloribus quibusdam quia nisi quasi aliquid ratione! Soluta quisquam incidunt, velit numquam, esse impedit doloremque provident optio reprehenderit. Totam eveniet ex sit iure, mollitia id aperiam magni error voluptate suscipit, reprehenderit placeat. Iure dolorum velit quae quibusdam aut soluta numquam eius tempora provident voluptatum, fugiat, nobis molestias! Optio, amet.`,
    href: '/labore-et-dolore-magnam-aliquam',
    image: 'https://picsum.photos/seed/picsum/200/300',
  },
  {
    title: 'Iure Voluptatem Error Omnis Eius',
    desc: `\t\tIure voluptatem error omnis eius. Sunt beatae soluta, vel sint magni doloribus? Neque, quaerat assumenda sequi perferendis id dolorem nam distinctio, alias dignissimos. Eum quaerat nisi accusamus voluptatum blanditiis optio doloribus exercitationem tempora recusandae, aliquid illo! Similique, commodi magni autem excepturi recusandae sint reiciendis deserunt tempora ex obcaecati. Labore eius repellat a delectus nam quos! Autem, dolore! Veniam voluptatum esse molestiae, fugit quas numquam expedita error consectetur. Labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident. Quod, necessitatibus! Qui cumque voluptates dolor amet magnam, itaque sunt impedit dolorem reprehenderit hic, velit mollitia deserunt ex beatae, esse nostrum tempore. Facilis fuga id delectus accusantium obcaecati magnam praesentium! Consectetur impedit voluptatum quaerat repellendus aliquam nobis quas officia, eveniet iure porro. Nulla aperiam corrupti a laboriosam, sequi minus deleniti obcaecati aut! Omnis tempora cum esse beatae dignissimos velit, provident unde placeat ipsam harum asperiores quasi voluptatibus. Velit esse cillum dolore eu fugiat nulla pariatur.
    
    \tExcepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Illum qui dolorem eum fugiat quo voluptas nulla pariatur. Asperiores aliquid quaerat, non totam optio porro, magni laborum, corrupti dignissimos. Sequi consequatur, voluptatem quaerat eius molestiae saepe, magnam optio rerum aliquam. Eius non distinctio sunt suscipit totam quae impedit atque, veritatis, doloribus? Tempore, accusantium. Facilis sunt deserunt reiciendis, eveniet ipsa voluptates. Quod debitis, atque odit sequi voluptatum, obcaecati vero dolorum impedit facilis veniam, quaerat tempora? Magnam distinctio dolore voluptatum alias error ut! Optio, voluptatibus veritatis tenetur suscipit doloribus quibusdam quia nisi quasi aliquid ratione! Soluta quisquam incidunt, velit numquam, esse impedit doloremque provident optio reprehenderit. Totam eveniet ex sit iure, mollitia id aperiam magni error voluptate suscipit, reprehenderit placeat. Iure dolorum velit quae quibusdam aut soluta numquam eius tempora provident voluptatum, fugiat, nobis molestias! Optio, amet.`,
    href: '/iure-voluptatem-error-omnis-eius',
    image: 'https://picsum.photos/seed/picsum/200/300',
  },
  {
    title: 'Est Illum Dolorum Sit Qui',
    desc: `\t\tEst illum dolorum sit qui. Amet iure ex magni, nam sed libero tenetur, voluptate similique laboriosam doloribus officiis. Reprehenderit distinctio, totam consequatur alias voluptate sequi rem perferendis quas necessitatibus accusantium expedita soluta voluptates, aspernatur esse. Odit, dolorum vel autem recusandae velit sequi, omnis aliquid praesentium aperiam totam! Ut nisi saepe pariatur sint, provident, fugiat accusantium quos tempore magni. Possimus, hic dolorum? Labore iure deserunt assumenda beatae perferendis voluptatibus. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus. Laboriosam non explicabo, qui quasi aut, debitis dignissimos accusantium laborum, alias voluptates suscipit distinctio, tempora! Voluptatum, maiores sapiente minus optio iusto beatae, expedita doloribus iure quisquam. Eos sunt, est sequi, voluptatibus excepturi aliquid officia quaerat impedit voluptates, vero mollitia? Nam consequuntur dolorum deserunt iusto facilis optio. Est quas beatae repudiandae fugiat distinctio voluptates optio pariatur optio dignissimos, ut porro. Voluptates consequatur atque, aut quis rerum non sit? Quod nobis minus omnis distinctio facilis ut, reprehenderit est. Accusantium nisi mollitia quaerat, reiciendis dolore. 
    
    \tTempore, soluta similique! Facilis iusto voluptates sunt laboriosam, mollitia voluptatum at numquam, necessitatibus totam delectus, quis laboriosam! Repudiandae eveniet distinctio quia doloremque molestias, commodi voluptatibus voluptas! Perferendis dolorem at beatae molestias omnis obcaecati error! Veniam, pariatur? Quas minus excepturi, magnam optio quos soluta tenetur dolorum non vero debitis. Ut sapiente corrupti aut consequuntur! Quia ipsa dolorum, doloremque ex architecto perferendis vero voluptatum saepe. Ex, dolorum consequatur. Accusantium quia pariatur minus velit, eius, voluptatum recusandae nobis. Obcaecati optio facilis aut omnis quas aperiam rerum totam dolore magni distinctio mollitia! Omnis velit labore ut iusto quaerat saepe eaque dignissimos sit, expedita ex doloribus!`,
    href: '/est-illum-dolorum-sit-qui',
    image: 'https://picsum.photos/seed/picsum/200/300',
  },
  {
    title: 'Explicabo Nemo Dolore Tempore Voluptas',
    desc: `\t\tExplicabo nemo dolore tempore voluptas. Molestias alias necessitatibus, officiis accusantium labore, quibusdam facilis sunt sint iusto excepturi porro debitis, velit atque quo temporibus? Sequi, possimus. Quaerat nihil alias perferendis vero, tenetur excepturi distinctio! Quod facilis eum distinctio ea, reprehenderit, delectus alias accusantium autem optio, amet quasi consectetur. Quibusdam quaerat voluptatum suscipit nostrum? Velit, culpa. Fugit aperiam eveniet, soluta temporibus laborum repudiandae est dolore? Illum nihil id consectetur quia dolor. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident. Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.
    
    \tLaboriosam magnam doloremque delectus quasi! Quasi optio quibusdam officia voluptates dolore error, nisi laborum commodi eaque impedit? Enim debitis optio aperiam dolores facere vero quos itaque, sint doloribus dolorum aliquid? Beatae, ratione eveniet voluptas maiores impedit debitis, reiciendis accusamus exercitationem dolorum iure aut. Repudiandae, ipsa perferendis, voluptatibus, atque nihil fugiat voluptates sequi sapiente reiciendis, tempora, obcaecati! Accusantium distinctio aperiam optio doloribus reprehenderit doloremque. Distinctio obcaecati harum est iure nisi reprehenderit. Eveniet, dolorum vel, molestias pariatur omnis doloribus, sequi voluptatum perferendis ut impedit. Reprehenderit vero consequatur, facilis nesciunt optio ex sit molestias, beatae quisquam aperiam dignissimos id. Optio repellat distinctio optio accusantium voluptas, voluptatibus consequuntur alias laboriosam. Delectus, officiis incidunt voluptatibus iure, numquam, sit tempora vero! Explicabo distinctio odit, dolorum beatae numquam tempora quaerat ex molestias perferendis laborum optio. Sunt sapiente accusamus minima voluptate excepturi ex beatae voluptates. Est nisi atque, debitis incidunt vero soluta`,
    href: '/explicabo-nemo-dolore-tempore-voluptas',
    image: 'https://picsum.photos/seed/picsum/200/300',
  },
];

export default beritas;
